# -*- coding: utf-8 -*-
"""ResumeClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yr3OmmWI-XpxcfLv-D0z8on9RZbt7IkJ

# Resume Classifier Project

## Imports
"""

!pip install PyPDF2
!pip install gradio-pdf
!pip install pymupdf
import tensorflow as tf, keras, numpy as np, pandas as pd
# import kagglehub
import nltk, os
from google.colab import files
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Dropout
import PyPDF2
from gradio_pdf import PDF
import re
import joblib
import os
import fitz
import gradio

"""## Dataset"""

# from google.colab import drive
# drive.mount('/content/drive')

# files.upload()

# !ls /content/drive/MyDrive/ResumeClassifier

# drive_path = '/content/drive/MyDrive/ResumeClassifier/resume-dataset'
# path = kagglehub.dataset_download("gauravduttakiit/resume-dataset", path=drive_path)
# !kaggle datasets download -d gauravduttakiit/resume-dataset
# !unzip dataset-name.zip -d /content/drive/MyDrive/ResumeClassifier

# file_path = '/content/drive/MyDrive/ResumeClassifier/UpdatedResumeDataSet.csv'

file_path = 'https://raw.githubusercontent.com/BrandonYChan/Resume-Screener/refs/heads/main/UpdatedResumeDataSet.csv'
resume_df = pd.read_csv(file_path)
resume_df['Category'].unique()

resume_df

# Clean text
resume_df['Resume'] = resume_df['Resume'].str.lower()
resume_df['Resume'] = resume_df['Resume'].str.replace(r'[^a-zA-z\s]', '', regex=True)
resume_df['Resume'] = resume_df['Resume'].str.strip().replace(r'\s', ' ', regex=True)

# Remove stopwords
nltk.download('stopwords')
stop_words = set(nltk.corpus.stopwords.words('english'))
resume_df['Resume'] = resume_df['Resume'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))

resume_df

"""##Model (initial idea)
####Step 1
feed cleaned input resume into a model (such as a neural network) trained on the dataset above, which classifies resumes into a category (e.g., Data Science).
####Step 2
If input resume matches the user-specified category, compare the resume to the job description by searching for key words/skills. If the similarity (e.g., cosine similarity) between the resume and job description is above a certain threshold, assign the resume as 'passable'. In all other cases, assign the resume as 'not passable'.
####Extra
Maybe we can allow the user to feed in a batch of submitted resumes for a job description, where the code would return a small subset of resumes accepted for interviews. These accepted resumes must have a matching category (assigned by the NN model) to the job description, and must also be the top-performers in terms of cosine similarity to the job description.
"""

# Additional imports

# !pip install PyPDF2
# !pip install gradio-pdf

# from sklearn.preprocessing import LabelEncoder
# from tensorflow.keras.utils import to_categorical
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.model_selection import train_test_split
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Input, Dense, Dropout
# import PyPDF2
# from gradio_pdf import PDF
# import re
# import joblib
# import os

# Encode labels
resume_df_encoded = resume_df.copy()
label_encoder = LabelEncoder()
resume_df_encoded['Category'] = label_encoder.fit_transform(resume_df_encoded['Category'])
Y = to_categorical(resume_df_encoded['Category'])
Y

# Extract features from text in Resume column
tfidf = TfidfVectorizer(max_features=5000) # limit number of features to the top 5000 words with the highest TF-IDF scores across the dataset
X = tfidf.fit_transform(resume_df_encoded['Resume']).toarray() # assign weights to words based on their frequency in a resume and rarity across all resumes
X # each row represents a resume, and each column represets a word's TF-IDF score; there are 5000 columns, each representing one of the top 5000 most important words

# Split data into 70% training, 15% val, 15% test
X_train, X_val, Y_train, Y_val = train_test_split(X, Y, test_size=0.3, random_state=13)
X_val, X_test, Y_val, Y_test = train_test_split(X_val, Y_val, test_size=0.5, random_state=13)
X_train.shape, Y_train.shape, X_val.shape, Y_val.shape, X_test.shape, Y_test.shape

model_path = '/model.pkl'

# Train model if it hasn't already been trained and saved
if not(os.path.exists(model_path)):
  # Feed data into NN
  model = Sequential([
      Input(shape=(X.shape[1],)),
      Dense(512, activation='relu'),
      Dropout(0.3),
      Dense(256, activation='relu'),
      Dropout(0.3),
      Dense(128, activation='relu'),
      Dropout(0.3),
      Dense(Y.shape[1], activation='softmax')
  ])
  model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
  history = model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=5, batch_size=16, verbose=True)
  joblib.dump(model, 'model.pkl')
else:
  # Load model if already saved into workspace
  model = joblib.load('model.pkl')

test_loss, test_accuracy = model.evaluate(X_test, Y_test)
print(f"Test Accuracy: {test_accuracy}, Test Loss: {test_loss}")

# Show prediction results of some random samples
random_indices = np.random.choice(X.shape[0], size=5, replace=False) # SRSWOR of 5 random row indices
sample_X = X[random_indices]
sample_Y = Y[random_indices]
predictions = model.predict(sample_X)
predicted_labels = label_encoder.inverse_transform(np.argmax(predictions, axis=1))
true_labels = label_encoder.inverse_transform(np.argmax(sample_Y, axis=1))
for i in range(5):
    print(f"Random Resume {i+1}:\n--Predicted = {predicted_labels[i]}\n--True = {true_labels[i]}")

"""## Testing Input"""

# # Import PDF of some random resume
# print("Select a resume to categorize:")
# upload = files.upload()
# file_path = list(upload.keys())[0]
# reader = PyPDF2.PdfReader(file_path)

# # nltk.download('stopwords')
# # stop_words = set(nltk.corpus.stopwords.words('english'))

# def evaluate_pdf(reader):
#   # Read resume text
#   resume_text = ''
#   for page in range(len(reader.pages)):
#       text = reader.pages[page].extract_text()
#       resume_text += text
#   # print("Resume text (original):\n", resume_text)

#   # Clean text (done in the same way as above in the Dataset section)
#   resume_text = resume_text.lower()
#   resume_text = re.sub(r'[^a-zA-z\s]', '', resume_text)
#   resume_text = re.sub(r'\s', ' ', resume_text).strip()

#   resume_text = ' '.join([word for word in resume_text.split() if word not in stop_words])
#   # print("\nResume text (cleaned):\n", resume_text)

#   # Categorize resume using the model
#   resume_text = tfidf.transform([resume_text]).toarray()
#   prediction = model.predict(resume_text)
#   predicted_label = label_encoder.inverse_transform(np.argmax(prediction, axis=1))
#   # print(f"\nImported Resume:\n--Predicted = {predicted_label}")
#   return predicted_label[0]
# evaluate_pdf(reader)

"""## Extracting Skills"""

df_skills = resume_df.groupby('Category').agg({'Resume':''.join})
df_skills

df_skills.loc['Data Science', ]['Resume']
# set(df_skills.loc['Data Science', :]['Resume'].split())

"""## Gradio App"""

#SKILLS = {"python", "machine learning", "data analysis", "sql", "tensorflow", "keras", "pandas", "numpy"} # need to avoid stating skills manually; look for libraries that allow us to retrieve a list of technical and soft skills across various industries

def preprocess_text(text):
    stop_words = set(nltk.corpus.stopwords.words('english'))
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

def extract_skills(text, skill_set):
    words = set(text.split())
    return words.intersection(skill_set)

def evaluate_resume(resume_file_path, position_opening, job_description):
    # load resume text
    resume_text = ""
    with fitz.open(resume_file_path) as resume:
        if resume.page_count == 0:
            return "PDF has no pages or could not be opened."

        for page_num in range(resume.page_count):
            page = resume[page_num]
            resume_text += page.get_text("text")  # extract text from each page

    # preprocess resume and job description text
    resume_text = preprocess_text(resume_text)
    #print("Resume text", resume_text)
    job_description = preprocess_text(job_description)
    #print("Job description", job_description)

    original_text = resume_text
    # extract skills
    #resume_skills = extract_skills(resume_text, SKILLS)
    #print("Resume skills", resume_skills)
    #job_skills = extract_skills(job_description, SKILLS)
    #print("Job skills", job_skills)

    # Categorize resume using the model
    resume_text = tfidf.transform([resume_text]).toarray()
    prediction = model.predict(resume_text)
    predicted_label = label_encoder.inverse_transform(np.argmax(prediction, axis=1))
    success=True if predicted_label == position_opening else False
    qualifications_match_html = f"""
          <div style="padding: 10px; color: white; text-align: center;
                      background-color: {'green' if success else 'red'};">
              {'Specialization Matches' if success else 'Specialization Does Not Match'}
          </div>
    """

    # Attempting with skills as all words in corresponding classified resume
    # If we can clean the text better to only have the skills portion this would work better
    skills_new = set(df_skills.loc[position_opening, :]['Resume'].split()) ########## New variable formed from skills of labeled resumes

    # Determine similarity in skills mentioned in job description with skills mentioned in resume
    #similar_skills = resume_skills.intersection(job_skills)
    #print('similar skills', similar_skills)
    #print('job skills', job_skills)
    #similarity_score = len(similar_skills) / len(job_skills) if job_skills else 0
    #similar_skills = "Python, Machine Learning, Data Analysis"

    # All matching skills
    similar_skills_resume = extract_skills(original_text, skills_new) ########## Modified version of variable
    similar_skills_job = extract_skills(job_description, skills_new) ########## Modified version of variable
    similar_skills = similar_skills_resume.intersection(similar_skills_job)
    similar_skills = ', '.join(similar_skills)
    similar_skills_resume = ', '.join(similar_skills_resume)
    similar_skills_job = ', '.join(similar_skills_job)
    #similarity_score = len(similar_skills) / len(skills_new) if len(skills_new)>0 else 0 ########## Modified version of variable
    similarity_score = len(similar_skills) / len(similar_skills_job) if len(similar_skills)>0 else 0 ########## Modified version of variable

    # similar_skills = job_skills
    #similarity_score = 0.85
    bar_color = 'green'
    # Create the similarity score HTML with dynamic coloring
    similarity_score_html = f"""
          <div>
              <strong>Similarity Score:</strong>
              <div style="width: 100%; background-color: #ddd;">
                  <div style="width: {similarity_score*100}%; background-color: {bar_color}; text-align: center; color: white;">
                      {similarity_score*100:.2f}%
                  </div>
              </div>
          </div>
    """

    return predicted_label[0], qualifications_match_html, similar_skills, similarity_score_html

# demo = gradio.Interface(
#     fn=evaluate_resume,
#     inputs=[PDF(label="Document"), gradio.Textbox(label="Position Name"), gradio.Textbox(label="Position Description")],
#     outputs= [gradio.Textbox(label="Specialization Prediction"), gradio.HTML(), gradio.Textbox(label="Matched Skills"), gradio.HTML()],
#     title="Resume Classifier"
# )
# demo.launch(debug=True)

demo = gradio.Interface(
    fn=evaluate_resume,
    inputs=[PDF(label="Document"),
            gradio.Dropdown(choices=['Data Science', 'HR', 'Advocate', 'Arts', 'Web Designing',
       'Mechanical Engineer', 'Sales', 'Health and fitness',
       'Civil Engineer', 'Java Developer', 'Business Analyst',
       'SAP Developer', 'Automation Testing', 'Electrical Engineering',
       'Operations Manager', 'Python Developer', 'DevOps Engineer',
       'Network Security Engineer', 'PMO', 'Database', 'Hadoop',
       'ETL Developer', 'DotNet Developer', 'Blockchain', 'Testing'],
                            label="Select a Position"),
            gradio.Textbox(label="Position Description")],
    outputs= [gradio.Textbox(label="Specialization Prediction"), gradio.HTML(), gradio.Textbox(label="Matched Skills"), gradio.HTML()],
    title="Resume Classifier"
)
demo.launch(debug=True)
